### ISSUE TITLE
Android Basics: SQL Basics

### ISSUE THREAD

**Issue by hebadi** [google-developer-training/android-basics-kotlin-sql-basics-app#12]
This sentence was included in the codelab section Primary Key:
"While you won't be using databases with more than one table in this course, having a unique ID which will also help with querying, updating, and deleting existing items in a table."
Problem with it is that it is an incomplete sentence and confusing to understand.

**Comment by osuleymanova** [comment]
@hebadi 
Thank you for reaching out to us. We fully understand your concern so the issue was fixed and published.
