### ISSUE TITLE
Android Basics: SQL Basics

### ISSUE THREAD

**Issue by matttzzz** [google-developer-training/android-basics-kotlin-sql-basics-app#18]
Downloading and attempting to build the project runs into an error message:

Execution failed for task ':app:kaptDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution
   > java.lang.reflect.InvocationTargetException (no error message)

I don't have the experience to troubleshoot it seems. I've tried googling and haven't been able to find the cause of the error unfortunately

**Comment by matttzzz** [comment]
Ah - just saw the previous issue and downgraded the room version with success.

**Comment by osuleymanova** [comment]
@matttzzz 
Thank you for reaching out to us and informing that the issue is fixed.
Happy coding!
