### ISSUE TITLE
A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution

### ISSUE THREAD

**Issue by huhuasd** [google-developer-training/android-basics-kotlin-sql-basics-app#20]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-sql-basics?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-5-pathway-1%3Fhl%3Den%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-sql-basics&hl=en#2

**In which task and step of the codelab can this issue be found?**
in step 3

**Describe the problem**
<img width="1229" alt="gambar" src="https://user-images.githubusercontent.com/52058660/143393034-af4fec92-6822-4a0b-b60e-318c6f636a6a.png">

**Steps to reproduce?**
when run app

**Versions**
_Android Studio version:_ Arctic Fox | 2020.3.1 Patch 3 (arm64 Preview)
_API version of the emulator:_ 31

**Comment by juansturla** [comment]
I have the same issue on a mac m1

Detailed error info

`
Caused by: java.lang.Exception: No native library is found for os.name=Mac and os.arch=aarch64. path=/org/sqlite/native/Mac/aarch64
	at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:333)`

**Comment by deckikwok** [comment]
same issue on m1 mac

**Comment by YaMaisiukDranko** [comment]
@deckikwok Thanks for help! You save my time 👍👍👍

**Comment by dogtim** [comment]
Yes, @deckikwok gives the answer

From Room Library: https://developer.android.com/jetpack/androidx/releases/room#version_240_3

- Fixed an issue with Room’s SQLite native library to support Apple’s M1 chips.
