### ISSUE TITLE
Android Basics: SQL Basics

### ISSUE THREAD

**Issue by jquinterom** [google-developer-training/android-basics-kotlin-sql-basics-app#21]
---
name: Android Basics Unit 5 issue
about: Report problems with the Android Basics Unit 5 codelabs
title: 'Android Basics Unit 5 issue:'
labels: ''
assignees: ''

---

**URL of codelab**
[URL](https://developer.android.com/codelabs/basic-android-kotlin-training-sql-basics?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-5-pathway-1%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-sql-basics#2)

**In which task and step of the codelab can this issue be found?**
In step 3

**Describe the problem**
In the end of page there is a route for open database inspector, but it doesn't exists because in my case the correct name is "App inspection" not "Database inspector"

**Steps to reproduce?**
1. Go to [URL](https://developer.android.com/codelabs/basic-android-kotlin-training-sql-basics?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-5-pathway-1%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-sql-basics#2)
2. Got to end of page
3. See "View > Tool Windows > Database Inspector." 

**Versions**
_Android Studio version: 2021.1.1 Canary 3
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
Page:
![image](https://user-images.githubusercontent.com/87286568/144156955-1de146e8-e140-4442-a9bf-005afe7f1301.png)

**Comment by alu0100207385** [comment]
> name: Android Basics Unit 5 issue about: Report problems with the Android Basics Unit 5 codelabs title: 'Android Basics Unit 5 issue:' labels: '' assignees: ''
> 
> **URL of codelab** [URL](https://developer.android.com/codelabs/basic-android-kotlin-training-sql-basics?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-5-pathway-1%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-sql-basics#2)
> 
> **In which task and step of the codelab can this issue be found?** In step 3
> 
> **Describe the problem** In the end of page there is a route for open database inspector, but it doesn't exists because in my case the correct name is "App inspection" not "Database inspector"
> 
> **Steps to reproduce?**
> 
> 1. Go to [URL](https://developer.android.com/codelabs/basic-android-kotlin-training-sql-basics?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-5-pathway-1%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-sql-basics#2)
> 2. Got to end of page
> 3. See "View > Tool Windows > Database Inspector."
> 
> **Versions** _Android Studio version: 2021.1.1 Canary 3 _API version of the emulator:_
> 
> **Additional information** _Include screenshots if they would be useful in clarifying the problem._ Page: ![image](https://user-images.githubusercontent.com/87286568/144156955-1de146e8-e140-4442-a9bf-005afe7f1301.png)

Hi jquinterom,
This view could be different according to your Android Studio version. For Android Studio 2020.3.1 Arctic Fox, View > Tool > App Inspection.
I can see two tabs: 'Database Inspector' and 'Background Task Inspector'.

[https://stackoverflow.com/questions/62355581/android-studio-database-inspector-does-not-show-any-databases](https://stackoverflow.com/questions/62355581/android-studio-database-inspector-does-not-show-any-databases)

**Comment by osuleymanova** [comment]
Hello @jquinterom,

Thanks for reaching out to us. The codelab content is updated:

![Screenshot 2023-03-09 at 3 27 11 PM](https://user-images.githubusercontent.com/86437155/224194942-d96fdb0f-14fd-4395-9815-39dcb7a25951.png)
