### ISSUE TITLE
Android Basics: SQL Basics

### ISSUE THREAD

**Issue by nehem10** [google-developer-training/android-basics-kotlin-sql-basics-app#27]
After Artic Fox Update, Database Inspector now can be opened by going to View-> Tool window -> App Inspection. Then after we launch the emulator then it opens the Database Inspector.

**Comment by osuleymanova** [comment]
Hello @nehem10,

Thanks for reaching out to us. The codelab content is updated:

![Screenshot 2023-03-09 at 3 27 11 PM](https://user-images.githubusercontent.com/86437155/224196461-b4855008-c5e1-4a3a-aaf0-27078a64c6c9.png)
