### ISSUE TITLE
Android Basics: SQL Basics

### ISSUE THREAD

**Issue by Bonfs** [google-developer-training/android-basics-kotlin-sql-basics-app#28]
Room version should be uptaded to version 2.4.2 for compatibility with Apple Silicon

**Comment by pd95** [comment]
Thank you for this hint. I had the following error after checking out the project:

    > Task :app:kaptDebugKotlin FAILED
    
    Execution failed for task ':app:kaptDebugKotlin'.
    > A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction
       > java.lang.reflect.InvocationTargetException (no error message)


After setting the the room version to 2.4.2 in `build.gradle (Module: SQL_Basics.app)` I could successfully build the project on an Apple Silicon Mac. Should we create a PR with that change ourselves or is somebody monitoring issues in this area?
