### ISSUE TITLE
Android Basics: SQL Basics

### ISSUE THREAD

**Issue by struyf** [google-developer-training/android-basics-kotlin-sql-basics-app#29]
Database inspector can't be found by the given instructions. Should be updated to App Inspection

**Comment by osuleymanova** [comment]
Hello @struyf,

Thanks for reaching out to us. The codelab content is updated:

![Screenshot 2023-03-09 at 3 27 11 PM](https://user-images.githubusercontent.com/86437155/224195266-07b808ba-3a46-4e31-9d9a-8cbc0f104bf6.png)
