### ISSUE TITLE
Android Basics: SQL Basics

### ISSUE THREAD

**Issue by Wavey1287** [google-developer-training/android-basics-kotlin-sql-basics-app#30]
This is now called App Inspection, not Database Inspector

**Comment by osuleymanova** [comment]
Hello @Wavey1287,

Thanks for reaching out to us. The codelab content is updated:

![Screenshot 2023-03-09 at 3 27 11 PM](https://user-images.githubusercontent.com/86437155/224194442-b247ae9a-2efa-4d4f-9c79-1d8cbca059e8.png)
