### ISSUE TITLE
Android Basics: SQL Basics

### ISSUE THREAD

**Issue by zXcongducXz** [google-developer-training/android-basics-kotlin-sql-basics-app#32]
there is no View > Tool Windows > Database Inspector.

**Comment by casti093** [comment]
View > Tool Windows > App Inspection

**Comment by osuleymanova** [comment]
Hello @zXcongducXz,

Thanks for reaching out to us. The codelab content is updated:

![Screenshot 2023-03-09 at 3 27 11 PM](https://user-images.githubusercontent.com/86437155/224194643-5afd0e34-14dd-46ed-a5d9-c22e5ad2326d.png)
