### ISSUE TITLE
Android Basics: SQL Basics

### ISSUE THREAD

**Issue by EpicDevTeam** [google-developer-training/android-basics-kotlin-sql-basics-app#39]
Last section, step 3. 
currently:
In Android Studio, open the Database Inspector with View > Tool Windows > Database Inspector.

should be:
In Android Studio, open the Database Inspector with View > Tool Windows > App Inspector. The Database Inspector is on this panel.
Note: app must be run on device with API 26+

bonus info:
For more information on working with this tool see: https://developer.android.com/studio/inspect/database

**Comment by EpicDevTeam** [comment]
Update: after continuing to read the instructions I did just see the green highlight box stating the different navigation. However, since only android studio version prior to 2020 arctic fox would have the current navigation it makes more sense to reverse which one is noted at the odd one out.

**Comment by osuleymanova** [comment]
Hello @EpicDevTeam,

Thanks for reaching out to us. The codelab content is updated:

![Screenshot 2023-03-09 at 3 27 11 PM](https://user-images.githubusercontent.com/86437155/224194186-2274aff3-39c6-4313-94db-173083ac6ff5.png)
