### ISSUE TITLE
Android Basics: SQL Basics

### ISSUE THREAD

**Issue by hamersun** [google-developer-training/android-basics-kotlin-sql-basics-app#4]
In section 5 (Common SQL functions)
below the SQL command 
```
SELECT SUM(park_visitors) FROM park
WHERE type = "national_park"
```
There is a typo in the description "It's worth **noting** that you can still use SUM()...". It should be **nothing**.

**Comment by paladaxar** [comment]
I think this line is actually correct.

The phrase "it's worth noting..." is an expression that means "it's worth mentioning..." which is what the author was trying to imply I believe. Now if you're talking about a null value being "worth nothing", then you're (pretty much) right :)

**Comment by hamersun** [comment]
@paladaxar  you are right. It is my misunderstanding.
