### ISSUE TITLE
Use SQL to read and write to a database

### ISSUE THREAD

**Issue by CyberButton** [google-developer-training/android-basics-kotlin-sql-basics-app#41]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-compose-sql?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-compose-unit-6-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-compose-sql#7

**In which task and step of the codelab can this issue be found?**
- Use SQL to read and write to a database
- - Insert, update, and delete data in a database

**Describe the problem**
At the beginning of this step of the codelab we created a new row in email with id 44 and in the last par we are asked to delete
a row with id 48, but such does not exist

**Steps to reproduce?**
if you just follow this part of the codelab from start to end you will eventually meet this probelm 
1. insert new row according to codelab: 
INSERT INTO email
VALUES (
    NULL, 'Lorem ipsum dolor sit amet', 'sender@example.com', 'inbox', false, false, CURRENT_TIMESTAMP
);
2. Observe that the result is inserted into the database with an id of 44.
3. Read the last part where it asks to delete the row with id 48: "Perform the following DELETE statement 
to delete the row with an id of 48 from the database."

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 
dont think it is necessary 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
yeah sure i'll include screenshot 
![Screenshot 2022-12-30 033304](https://user-images.githubusercontent.com/67738637/210013123-ccfb1e6c-f5f9-4dd3-aa60-c3e8e5defcc4.png)
![Screenshot 2022-12-30 033334](https://user-images.githubusercontent.com/67738637/210013129-5432a43c-52b2-42e7-8dfe-cca91958dcc3.png)

**Comment by osuleymanova** [comment]
Hello @CyberButton,

Thanks for reaching out to us and reporting this issue. It is fixed and republished:

![Screenshot 2023-03-09 at 4 35 54 PM](https://user-images.githubusercontent.com/86437155/224193344-f5a6c26c-42b0-41a0-86ea-aca498c11e61.png)
