### ISSUE TITLE
Android Basics: SQL: APP inspection not Database... in newer versions

### ISSUE THREAD

**Issue by TiffanyTesla** [google-developer-training/android-basics-kotlin-sql-basics-app#48]
in more recent versions, it appears that name changed to APP inspection. Same pathway.
![Screenshot 2023-02-21 135438](https://user-images.githubusercontent.com/115897098/220434087-4711c1c6-3fd1-4633-a3d4-80a760f72315.png)

**Comment by osuleymanova** [comment]
Hello @TiffanyTesla,

Thanks for reaching out to us. The codelab content is updated:
![Screenshot 2023-03-09 at 3 27 11 PM](https://user-images.githubusercontent.com/86437155/224183788-05e8feec-eb17-4392-aeb0-e7df5a9360bd.png)
