### ISSUE TITLE
Incorrect "What's Next" Video

### ISSUE THREAD

**Issue by cjparent** [google-developer-training/android-basics-kotlin-sql-basics-app#50]
I apologize, I am not sure where else to elevate issues with the videos 

**URL of codelab**
https://developer.android.com/courses/pathways/android-basics-compose-unit-6-pathway-1#codelab-https://developer.android.com/codelabs/basic-android-kotlin-compose-sql

**In which task and step of the codelab can this issue be found?**
The "What's next?" video

**Describe the problem**
The "What's next" video is incorrect. It is currently the video also found in the "Get Data from the Internet" pathway of Unit 5

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

Both videos are linked to : https://www.youtube.com/watch?v=mQBQATHQgSc

**Comment by osuleymanova** [comment]
Hello @cjparent,

The issue that you presented to us is extremely important, and I thank you for bringing it to our attention. The videos will be updated soon with the correct links.
