### ISSUE TITLE
Android Basics: SQL Basics

### ISSUE THREAD

**Issue by M-Phuykong** [google-developer-training/android-basics-kotlin-sql-basics-app#6]
2/ Overview of a relational database
 
It seems like the table is messed up.
![Capture](https://user-images.githubusercontent.com/53167700/128292777-e92c8be8-4357-4442-a80a-88486e10fc54.PNG)

**Comment by osuleymanova** [comment]
@M-Phuykong 
Thank you for reaching out to us. The issue is fixed and published.
