### ISSUE TITLE
Android Basics: SQL Basics - Step 5

### ISSUE THREAD

**Issue by paladaxar** [google-developer-training/android-basics-kotlin-sql-basics-app#9]
The text reads:
`use the COUNT() function and pass in * (for all rows) or a row name, and the query will instead return a count of all rows`

This sentence should say "...or a column name..." instead of "...or a row name...".

Thanks for this great intro to Android Apps course! I'm really enjoying it! :)

**Comment by osuleymanova** [comment]
@paladaxar 
Thank you for reaching out to us. The issue is fixed and published:
https://android.devsite.corp.google.com/codelabs/basic-android-kotlin-training-sql-basics#4

We really appreciate your feedback as well.
